# Generated by Django 5.2.10 on 2026-03-13 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_budget_project_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="County",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "counties",
                "db_table": "project_counties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(blank=True, max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "project_regions",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("affordable_housing", "Affordable Housing"),
                    ("infrastructure", "Infrastructure"),
                    ("commercial", "Commercial"),
                    ("residential", "Residential"),
                    ("mixed_use", "Mixed-Use"),
                    ("health", "Health"),
                    ("education", "Education"),
                    ("water_sanitation", "Water & Sanitation"),
                    ("energy", "Energy"),
                    ("ict", "ICT"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="client_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="project",
            name="owner_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("government", "Government"),
                    ("private", "Private"),
                    ("ngo", "NGO"),
                    ("ppp", "Public–Private Partnership"),
                    ("faith_based", "Faith-Based / CBO"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="progress",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="sector",
            field=models.CharField(
                blank=True,
                choices=[
                    ("housing", "Housing"),
                    ("infrastructure", "Infrastructure"),
                    ("health", "Health"),
                    ("education", "Education"),
                    ("commercial", "Commercial"),
                    ("water", "Water & Sanitation"),
                    ("energy", "Energy"),
                    ("transport", "Transport"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="sponsor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("active", "Active"),
                    ("on_hold", "On Hold"),
                    ("at_risk", "At Risk"),
                    ("completed", "Completed"),
                    ("closed", "Closed"),
                    ("in_progress", "In Progress"),
                    ("cancelled", "Cancelled"),
                ],
                default="planned",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="county",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="projects.county",
            ),
        ),
        migrations.AlterField(
            model_name="projectsite",
            name="county",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sites",
                to="projects.county",
            ),
        ),
        migrations.AddField(
            model_name="county",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="counties",
                to="projects.region",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="projects.region",
            ),
        ),
        migrations.CreateModel(
            name="SubCounty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcounties",
                        to="projects.county",
                    ),
                ),
            ],
            options={
                "db_table": "project_subcounties",
                "ordering": ["name"],
                "unique_together": {("name", "county")},
            },
        ),
        migrations.AddField(
            model_name="project",
            name="subcounty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="projects.subcounty",
            ),
        ),
        migrations.AddField(
            model_name="projectsite",
            name="subcounty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sites",
                to="projects.subcounty",
            ),
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subcounty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wards",
                        to="projects.subcounty",
                    ),
                ),
            ],
            options={
                "db_table": "project_wards",
                "ordering": ["name"],
                "unique_together": {("name", "subcounty")},
            },
        ),
        migrations.AddField(
            model_name="project",
            name="ward",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="projects.ward",
            ),
        ),
        migrations.AddField(
            model_name="projectsite",
            name="ward",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sites",
                to="projects.ward",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="county",
            unique_together={("name", "region")},
        ),
    ]
