# Generated by Django 5.2.12 on 2026-03-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0003_county_region_alter_project_options_project_category_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="ward",
        ),
        migrations.RemoveField(
            model_name="projectsite",
            name="ward",
        ),
        migrations.AlterModelOptions(
            name="subcounty",
            options={"ordering": ["name"], "verbose_name_plural": "sub counties"},
        ),
        migrations.AlterUniqueTogether(
            name="county",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="project",
            name="subcounty",
        ),
        migrations.RemoveField(
            model_name="projectsite",
            name="subcounty",
        ),
        migrations.AlterUniqueTogether(
            name="subcounty",
            unique_together={("county", "name")},
        ),
        migrations.AddField(
            model_name="projectsite",
            name="county_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="county",
            name="code",
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="county",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name="Ward",
        ),
        migrations.RemoveField(
            model_name="subcounty",
            name="code",
        ),
        migrations.RemoveField(
            model_name="subcounty",
            name="created_at",
        ),
    ]
