# Generated by Django 5.2.12 on 2026-03-14 13:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_remove_project_ward_remove_projectsite_ward_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subcounty",
            unique_together={("name", "county")},
        ),
        migrations.AddField(
            model_name="project",
            name="sub_county",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="projects.subcounty",
            ),
        ),
        migrations.AddField(
            model_name="projectsite",
            name="sub_county",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sites",
                to="projects.subcounty",
            ),
        ),
        migrations.AddField(
            model_name="subcounty",
            name="code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="subcounty",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sub_county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wards",
                        to="projects.subcounty",
                    ),
                ),
            ],
            options={
                "db_table": "project_wards",
                "ordering": ["name"],
                "unique_together": {("name", "sub_county")},
            },
        ),
        migrations.AddField(
            model_name="project",
            name="ward",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="projects.ward",
            ),
        ),
        migrations.AddField(
            model_name="projectsite",
            name="ward",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sites",
                to="projects.ward",
            ),
        ),
    ]
