# Generated by Django 5.2.12 on 2026-03-17 15:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0005_alter_subcounty_unique_together_project_sub_county_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("affordable_housing", "Affordable Housing"),
                    ("infrastructure", "Infrastructure"),
                    ("commercial", "Commercial"),
                    ("residential", "Residential"),
                    ("mixed_use", "Mixed-Use"),
                    ("health", "Health"),
                    ("education", "Education"),
                    ("water_sanitation", "Water & Sanitation"),
                    ("energy", "Energy"),
                    ("ict", "ICT"),
                    ("trade", "Trade"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ProjectSiteMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("file", models.FileField(upload_to="project_media/")),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("video", "Video"),
                            ("document", "Document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="projects.project",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="projects.projectsite",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "project_site_media",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
