# Generated by Django 5.2.9 on 2025-12-19 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0001_initial"),
        ("projects", "0002_project_budget_project_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailyprogress",
            options={"ordering": ["-report_date"]},
        ),
        migrations.RenameField(
            model_name="dailyprogress",
            old_name="date",
            new_name="report_date",
        ),
        migrations.RenameField(
            model_name="dailyprogress",
            old_name="description",
            new_name="work_done_description",
        ),
        migrations.AlterUniqueTogether(
            name="dailyprogress",
            unique_together={("project", "report_date")},
        ),
        migrations.AddField(
            model_name="dailyprogress",
            name="actual_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Actual cost incurred for the day (KES)",
                max_digits=15,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dailyprogress",
            name="actual_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Actual % completion achieved",
                max_digits=5,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dailyprogress",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dailyprogress",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyprogress",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_progress_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dailyprogress",
            name="planned_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Planned % completion for the day",
                max_digits=5,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dailyprogress",
            name="reported_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="progress_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dailyprogress",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="dailyprogress",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_reports",
                to="projects.project",
            ),
        ),
        migrations.RemoveField(
            model_name="dailyprogress",
            name="created_by",
        ),
    ]
