# Generated by Django 5.2.9 on 2025-12-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Project Manager'), ('engineer', 'Engineer'), ('qa', 'QA/QC'), ('finance', 'Finance'), ('CLIENT', 'Client')], default='CLIENT', max_length=20),
        ),
    ]
