# Generated by Django 5.2.9 on 2025-12-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Project Manager"),
                    ("engineer", "Engineer"),
                    ("qa", "QA/QC"),
                    ("finance", "Finance"),
                    ("CLIENT", "Client"),
                ],
                default="CLIENT",
                max_length=20,
                null=True,
            ),
        ),
    ]
